runtime: python
env: flex
entrypoint: gunicorn -b :$PORT nammaooruspecial.wsgi:application

runtime_config:
  python_version: 3.7

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
  secure: always
